delivery_package/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.contrib.auth.views import LogoutView
from apps.general.views.general_views import change_password_form, change_password_view, login_view

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('login/',login_view,name='login_view'),
    
    path('logout/',LogoutView.as_view(),name='logout'),
    path('change_password/',change_password_view,name='change_password_view'),
    path('change_password_form/',change_password_form,name='change_password_form'),
    path('',include('apps.general.dashboard_urls')),
]

apps/package/models.py
from django.db import models
from django.core.validators import MinValueValidator
import uuid


def generate_delivery_code():
    while True:
        delivery_code = str(uuid.uuid4().int)[:8]  # Trunca el UUID a 8 caracteres
        if not Customer.objects.filter(delivery_code=delivery_code).exists():
            break
    return delivery_code


# Create your models here.
class Customer(models.Model):
    full_name = models.CharField(max_length=120)
    phone_number = models.CharField(max_length=20,null=False,blank=False,unique=True)
    address=models.CharField(max_length=150,null=True,blank=True)
    email = models.EmailField(unique=True,null=True,blank=True)
    delivery_code = models.CharField(max_length=8,null=True,blank=True)
    
    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

    def __str__(self):
        return self.full_name

    def save(self, *args, **kwargs):
        if not self.delivery_code:
            self.delivery_code = generate_delivery_code()
        super().save(*args, **kwargs)
    
class Addressee(models.Model):
    full_name = models.CharField(max_length=120)
    province = models.CharField(max_length=20)
    municipe = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20,unique=True)
    address=models.CharField(max_length=150)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE,related_name='custommer_addressee')
    
    class Meta:
        verbose_name = "Destinatario"
        verbose_name_plural = "Destinatarios"

    def __str__(self):
        return self.full_name
        
    
class Package(models.Model):
    PAYMENT_STATE=(
        ('1','pendiente'),
        ('2','pagado'),
    )
    STATE=(
        ('1','en proceso'),
        ('2','completado'),
        ('3','entregado')
        
    )
    TYPE=(
        ('1','marítimo'),
        ('2','aéreo'),
        ('3','aéreo express')
    )
    PAYMENT_METHOD=(
        ('1','efectivo'),
        ('2','transferencia'),
        ('3','tarjeta'),
    )
    
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE,related_name='custommer_package')
    addressee = models.ForeignKey(Addressee,on_delete=models.CASCADE,related_name='addressee_package')
    cost = models.FloatField(validators=[MinValueValidator(0)])
    weight = models.FloatField(validators=[MinValueValidator(0)])
    tax = models.FloatField(validators=[MinValueValidator(0)])
    message = models.TextField(null=True,blank=True)
    bulk = models.PositiveIntegerField(default=0)
    state = models.CharField(max_length=1, choices=STATE,default='1')
    created_at= models.DateTimeField(auto_now=True)
    is_delivery = models.BooleanField(default=False)
    type = models.CharField(max_length=1, choices=TYPE,default='1')
    payment_state = models.CharField(max_length=1, choices=PAYMENT_STATE,default='1')
    payment_method = models.CharField(max_length=1, choices=PAYMENT_METHOD,default='1')
    payment_datetime= models.DateTimeField(auto_now=False,null=True,blank=True)
    delivery_datetime = models.DateTimeField(auto_now=False,null=True,blank=True)
    delivery_user_pk =  models.CharField(max_length=20,null=True,blank=True)
    delivery_user_username =  models.CharField(max_length=255,null=True,blank=True )
    delivery_user_email =   models.CharField(max_length=255,null=True,blank=True )
    
    class Meta:
        verbose_name = "Paquete"
        verbose_name_plural = "Paquetes"

    def __str__(self):
        return f"{self.pk}"
    
    @property
    def total_price(self):
        return round((self.cost * self.weight) + self.tax,2)
    
    @property
    def is_completed(self):
        if self.payment_state == '2' and self.bulk !=0:
            return True
        return False
    
class ImagePackage(models.Model):
    package = models.ForeignKey(Package,on_delete=models.CASCADE,related_name='image_package')
    image = models.ImageField(upload_to='image_package/')
    
    
    class Meta:
        verbose_name = "Imágen"
        verbose_name_plural = "Imágenes"

    def __str__(self):
        return f"{self.pk}"
    

class Order(models.Model):
    STATE=(
        ('1','gestionando'),
        ('2','en camino'),
        ('3','entregado'),
    )
    TYPE=(
        ('1','marítimo'),
        ('2','aéreo'),
        ('3','aéreo express')
    )
    type = models.CharField(max_length=1, choices=TYPE,default='1')
    state = models.CharField(max_length=1, choices=STATE,default='1')
    sent_date= models.DateField(auto_now=False,null=True,blank=True)
    delivery_date= models.DateField(auto_now=False,null=True,blank=True)
    packages = models.ManyToManyField(Package,blank=True,related_name='orders')
    
    class Meta:
        verbose_name = "Envío"
        verbose_name_plural = "Envíos"

    def __str__(self):
        return f"{self.pk}"
    
    @property
    def total_price(self):
        return round(sum(package.total_price for package in self.packages.all()) or 0 ,2)
    
    @property
    def total_packages(self):
        return self.packages.all().count()
    
    @property
    def bg_proccess(self):
        if self.state == '1':
            return 'list-group-item-success '
        elif self.state == '2':
            return 'list-group-item-info '
        else: 
            return 'list-group-item-primary'
        

apps/package/views/orders_successfull_views.py
from apps.account.models import User
from apps.package.filters import OrderFilter
from apps.package.forms.package_forms import  CreateOrderForm, PackageForm, UpdateOrderForm
from apps.package.models import  Order, Package
from django.shortcuts import render,get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
import logging
from apps.account.decorators import group_required
from utils.paginator import _create_paginator
logger = logging.getLogger(__name__)
from django.db.models import Q
from django.utils.translation import gettext as _
  
# orders index 
@group_required('administrador','gestor')
@staff_member_required(login_url='/')
def orders_successfull_views(request):
    context={}
    response= render(request,'orders_successfull/order.html',context)
    response['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
    response['Pragma'] = 'no-cache'
    response['Expires'] = '0'
    return response

# orders search result
@staff_member_required(login_url='/')
def orders_successfull_results_view(request):
    orders,context=_show_orders_successfull(request)
    context['item_total_count']=sum(order.total_packages for order in orders)
    context['item_total_price']=sum(order.total_price for order in orders)
    return  render(request,'orders_successfull/order_result.html',context)
       
# orders search funtion
@staff_member_required(login_url='/')
def _show_orders_successfull(request):
    orders = OrderFilter(request.GET, queryset=Order.objects.filter(state='3').order_by('-pk'))
    return orders.qs ,_create_paginator(request,orders)
    
   


# order detail forms
@group_required('administrador','gestor')
@staff_member_required(login_url='/')
def orders_successfull_detail(request,pk):
    order = Order.objects.filter(pk=pk,state='3').first()
    context={'order':order}
    return render(request,'orders_successfull/actions/orderDetail/orderDetail.html',context) 

apps/package/views/orders_views.py
from apps.account.models import User
from apps.package.filters import OrderFilter
from apps.package.forms.package_forms import  CreateOrderForm, PackageForm, UpdateOrderForm
from apps.package.models import  Order, Package
from django.shortcuts import render,get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
import logging
from apps.account.decorators import group_required
from utils.paginator import _create_paginator
from utils.send_email import order_in_proccess_send_customer_email, send_email_to_customer
logger = logging.getLogger(__name__)
from django.db.models import Q
from django.utils.translation import gettext as _
from datetime import date
  
# orders index 
@group_required('administrador','gestor')
@staff_member_required(login_url='/')
def orders_view(request):
    orders = Order.objects.filter(state__in=['1','2']).order_by('-id')
    context = {
        'admin':User.objects.all(),
        'orders':orders,
        'form': CreateOrderForm(),
        'packages': Package.objects.filter(state='2').exclude(orders__isnull=False).order_by('pk')
        }
    response= render(request,'orders_proccess/order.html',context)
    response['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
    response['Pragma'] = 'no-cache'
    response['Expires'] = '0'
    return response

# orders search result
@staff_member_required(login_url='/')
def orders_results_view(request):
    return  render(request,'orders_proccess/order_result.html',context=_show_orders(request))
       
# orders search funtion
@staff_member_required(login_url='/')
def _show_orders(request):
    return _create_paginator(request,OrderFilter(request.GET, queryset=Order.objects.filter(state__in=['1','2']).order_by('-pk')))
    
   


# order detail forms
@group_required('administrador','gestor')
@staff_member_required(login_url='/')
def order_detail(request,pk):
    order = Order.objects.filter(pk=pk,state__in=['1','2']).first()
    context={'order':order}
    return render(request,'orders_proccess/actions/orderDetail/orderDetail.html',context) 


# order detail forms
@group_required('administrador','gestor')
@staff_member_required(login_url='/')
def order_component_table_detail(request,pk):
    order = Order.objects.filter(pk=pk,state__in=['1','2']).first()
    context={'order':order}
    return render(request,'orders_proccess/order_table_component.html',context) 

# order detail forms
@group_required('administrador','gestor')
@staff_member_required(login_url='/')
def order_component_table_update_to_finished(request,pk):
    order = Order.objects.filter(pk=pk,state__in=['1','2']).first()
    context={'order':order}
    if order:
        if order.state=='1':
            order.state='2'
            order_in_proccess_send_customer_email(order)    
        else:
            order.state='3'
            order.delivery_date = date.today()
        order.save()
        if order.state == '3':
            order = []
        context['order']=order
    return render(request,'orders_proccess/order_table_component.html',context) 


# Delete order result table
@group_required('administrador')
@staff_member_required(login_url='/')
def order_delete(request,pk):
    order = Order.objects.filter(pk=pk).first()
    context={
        'order':order,
        
    }
    if request.method == "POST":
        if order:
            order.delete()
            context['order']=[]
            return  render(request,'orders_proccess/order_table_component.html',context)
    return  render(request,'orders_proccess/actions/orderDelete/orderDeleteVerify.html',context)


# Create order result table
@group_required('administrador')
@staff_member_required(login_url='/')
def order_create(request):
    form = CreateOrderForm()
    context={
        'form':form,
    }
    if request.method == "POST":
        form = CreateOrderForm(request.POST)
        if form.is_valid():
            form.save()
            context['message']='Envío creado correctamente'
    context['packages']=Package.objects.filter(state='2',type='1').exclude(orders__isnull=False).order_by('pk')
    return  render(request,'orders_proccess/actions/orderCreate/orderCreateForm.html',context)

# order get package

@group_required('administrador','gestor')
@staff_member_required(login_url='/')
def order_get_package(request):
    type =request.GET.get('type',None) 
    packages = Package.objects.filter(state='2',type=type).exclude(orders__isnull=False).order_by('-pk') if type  else []
    context={'packages':packages}
    return render(request,'orders_proccess/actions/orderCreate/select_package.html',context) 

# order update forms
@group_required('administrador','gestor')
@staff_member_required(login_url='/')
def order_update(request,pk):
    order = Order.objects.filter(pk=pk).first()
    context={
        'form':UpdateOrderForm(instance=order),
        'order':order,
        'packages': Package.objects.filter(state='2',type=order.type).exclude(orders__isnull=False).order_by('pk'),
        'select_packages': Package.objects.filter(state='2').filter(orders=order).order_by('pk')
        }
    if request.method == 'POST':
        form =   UpdateOrderForm(request.POST,instance=order)
        if form.is_valid():
            form.save()
            if order.state == '3':
                order.delivery_date = date.today()
                order.save()
            order_in_proccess_send_customer_email(order)      
            context['form']=form
            context['message']="Editado correctamente"
        
    return render(request,'orders_proccess/actions/orderUpdate/orderUpdateForm.html',context) 

templates/orders_successfull/order.html
{% extends "base_admin.html" %}
{% load static %}

{% block title %} Envíos {% endblock %}
{% block contend %}
  {% include "orders_successfull/actions/orderDetail/offcanvasRightOrderDetail.html" %}
  
  

   
  <form class="row g-3 mb-2"
  method="GET"
  id="OrderFilters"
  hx-get="{% url 'orders_successfull_results_view' %}"
  hx-target="#OrderResults"
  hx-swap="innerHTML"
  hx-trigger="submit"
  hx-indicator="#spinnerOrderFilter,#spinner">

<div class="col-12 col-sm-6 col-md-4 col-lg-3">
  <label for="inputOrderCodeFilter" class="form-label">Código</label>
  <input type="text" name="pk" class="form-control" id="inputOrderCodeFilter" placeholder="Código">
</div>
<div class="col-6 col-sm-4 col-md-4 col-lg-3">
  <label for="inputOrderCreateDate1Filter" class="form-label">Fecha (envio) inicio</label>
  <input type="date" name="sent_date_after" class="form-control" id="inputOrderCreateDate1Filter" placeholder="Create date 1">
</div>
<div class="col-6 col-sm-4 col-md-4 col-lg-3">
  <label for="inputOrderCreateDate2Filter" class="form-label">Fecha (envío) final</label>
  <input type="date" name="sent_date_before" class="form-control" id="inputOrderCreateDate2Filter" placeholder="Create date 2">
</div>



<div class="col-12">
<small class=" w-100 d-flex justify-content-end mt-3">
  <button type="submit" class="btn d-flex justify-content-center align-items-center btn-outline-primary shadow-sm border-2 border-primary px-5">
    <span id="spinnerOrderFilter" class="htmx-indicator spinner-border spinner-border-sm me-2" ></span>Filtrar</button>
</small>
</div>
</form>
  
 <div 
 hx-get="{% url 'orders_successfull_results_view' %}"
 hx-target="#OrderResults"
 hx-trigger="load"
 hx-swap="innerHTML"
 hx-indicator="#spinner"></div>
    
  <div class="w-100 position-relative d-flex justify-content-center align-items-start mb-5 pb-5" style="min-height: 200px !important;" >
    <div id="spinner" class="htmx-indicator w-100 h-100  loadding-blur position-absolute z-10 d-flex justify-content-center align-items-center"
    style="min-height: 200px !important;z-index: 100;">
      <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
    
    <div class="w-100 mt-3" id="OrderResults">
      
    </div>  
    </div>
    
     

  

  


  


 
    
{% endblock contend %}

        

templates/orders_successfull/order_table_component.html
{% load static %}

{% if order %}
  <tr class="text-center" id="TableOrder{{order.pk}}">
    <td class="border small ">{{order.pk}}</td>
    <td class="border small table-min">{{order.get_type_display}}</td>
    <td class="border small table-min">{{order.sent_date}}</td>
    <td class="border small table-min d-flex justify-content-around">
      <span class=" span-1 rounded-4 list-group-item small p-1 {{order.bg_proccess}}">
        {{order.get_state_display}}
        </span>
       </td>
    <td class="border small table-min ">$ {{order.total_price}}</td>
    <td class="border small table-min ">
      {{order.total_packages}}
          {% if order.packages.all %}
                       
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="border-2 rounded-1 border border-primary-subtle text-primary cursor-pointer bi-plus" viewBox="0 0 16 16"
                  tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-title="Paquetes" 
                  data-bs-content="{% for package in order.packages.all %}{{ package.pk }}{% if not forloop.last %}, {% endif %} {% endfor %}">
                  <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                </svg>
                          
                <script>
          
                  if (!window.popoverTriggerList) {
                    const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
                    const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
                  }
                  
                </script>
                    {% endif %}
    </td>
    
   
    
    <td class="table-width-80 px-1 ">
    <div class="d-flex justify-content-around  align-items-center p-0 m-0 pt-1">
        
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="cursor-pointer bi text-info bi-eye-fill"   
            viewBox="0 0 16 16" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRightOrderDetail" aria-controls="offcanvasRight"
            
            hx-get="{% url 'orders_successfull_detail' pk=order.pk  %} " 
            hx-target="#OrderDetail"
            hx-swap="innerHTML"
            hx-trigger="click"
            hx-indicator="#spinnerOrderDetail"
          >
            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"/>
            <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"/>
          </svg>
        
    </div>
    </td>
  </tr>
  
{% endif %}